### ISSUE TITLE
Explanation file 

### ISSUE THREAD

**Issue by EduardTheFirst** [openrazer/razer-drivers#1621]
hey guys i have a suggestion 

please try to understand me
i know a bit of coding and i have plenty of time 
but i think that we need to make the whole process of adding support for devices even more simple
so basically what i want to understand is what i need to do to add a device 
from a to z
and then i would crate a manual for people like me to add a keyboard and mice

**Comment by z3ntu** [comment]
Hi, I am aware that the process of adding new devices is quite convoluted and not really documented anywhere.
What I recommend people is to look at recent device support pull requests which show what needs to be done relatively well. And a lot of adding support unfortunately comes down to trial & error and fixing problems that pop up. I try to give some input based on the pcap if one was provided (like which transaction id to use, some of the functions to use, etc) but even with that some trial&error is necessary to get anything working. 
It was easier back with Synapse 2 because Synapse called more functions in the device firmware but with Synapse 3 they basically just do everything in software and just send the calculated frames to the hardware while openrazer still uses the hardware effects as they make way more sense for standards use cases in my opinion.
I hope I could help you, if you have any further questions don't hesitate to ask and I'll try to help you.
