### ISSUE TITLE
Linux Mint help with Tartarus Pro

### ISSUE THREAD

**Issue by EighterMOA** [openrazer/razer-drivers#1709]
Hello everyone!!
Fairly new to linux but being self taught :shrug: 

I have a question, I am trying to get my Razer tartarus pro to work in Linux mint.  I followed the instructions  in the screenshot below.  I dont really know what to do after this, I don't know how to "run" the program or where to go from here.  Any guidance would be appreciated!!  TIA
![image](https://user-images.githubusercontent.com/96300844/146560293-c6852a58-b1eb-4685-b3e9-e2b854349782.png)

**Comment by lah7** [comment]
Hello! OpenRazer on its own is just a driver and daemon for other applications/scripts to interact with. You'll need to install an application ("front end"). Choose one of your liking as listed [near the top of the homepage](https://openrazer.github.io/) or from the [README](https://github.com/openrazer/openrazer#applications).

Since you have a Tartarus keypad, OpenRazer doesn't offer a key rebinding facility, since it's mainly focused on lighting. Key mapping is fairly generic, [key-mapper](https://github.com/sezanzeb/key-mapper) seems to be a popular choice.

**Comment by EighterMOA** [comment]
Thanks!!!!  That is all I want is to remap my keys.  I'll try key mapper
and see what I can break :-)

**Comment by EighterMOA** [comment]
So i have key mapper installed.  When i push the numerical keys on the
keypad to remap them, it does not register anything.   when I push the
thumb buttons it works fine.  am i missing something?

**Comment by lah7** [comment]
Razer's keypads normally behave like keyboards, so it should emit regular key strokes.

I just realised that you said Tartarus **Pro** (I originally misread as the original Tartarus). Turns out your device isn't supported by OpenRazer yet (#1039, WIP in #1577) so lighting won't configurable, but it _should_ act as a generic input device.

You could try uninstalling OpenRazer since it's no use for your keypad right now. Pressing CTRL+ALT+T and using the Terminal is one way to do that:

    sudo apt autoremove openrazer-meta openrazer-driver-dkms python3-openrazer 

You could also try asking the folks in https://github.com/openrazer/openrazer/issues/1039#issuecomment-979505624 who own this keypad to see if they have any advice.

**Comment by EighterMOA** [comment]
Thanks for the tip!  I got the keys to remap, was missing some
dependencies.   To be very honest I could give a F about lighting. Just the
keys.  Thanks for all your help.  Merry Christmas!!
