### ISSUE TITLE
Disable Volume Wheel on BlackWidow Elite?

### ISSUE THREAD

**Issue by jackz314** [openrazer/razer-drivers#1748]
### Distribution

Ubuntu 21.10

### Support

I've started to have trouble with the volume wheel of the keyboard recently where it changes the volume by itself randomly, and apparently I'm not alone ([example](https://www.reddit.com/r/razer/comments/bp0h26/huntsman_elite_volume_wheel_becomes_scroll/)). Anyways, I'm just wondering if there's a way to disable the volume wheel in some way through openrazer?

I tried [input-remapper](https://github.com/sezanzeb/input-remapper) and [xmodmap](https://superuser.com/a/775811/1015995), but it appears the volume wheel is different from regular keys and can't be controlled through these ways.

**Comment by wyattearp** [comment]
Actually just had a similar thing happen on my BlackWidow Pro V3, but the volume wheel has some how remapped to mouse scroll. I think it might be something more than just a specific keyboard.

**Comment by drewstaylor** [comment]
It's a mechanical issue and Razer continues to refuse to offer any help or support. The level of not caring about a very real issue that makes the product unusable is just unreal.

**Comment by jackz314** [comment]
I think this is still a pretty significant issue for people, would someone be able to look into this more?

**Comment by wyattearp** [comment]
As a note - I have been able to improve the performance of the volume wheel by using contact cleaner. After cleaning, mute & volume control were 100% accurate.

**Comment by z3ntu** [comment]
@wyattearp For BlackWidow V3 this should've been fixed a while ago with #1751 and e.g. Ornata Chroma V2 with #1547. Can you make sure you're on the latest version and also provide `lsusb | grep 1532` ?

**Comment by wyattearp** [comment]
@z3ntu - TL;DR - I'd recommend closing.

I can confirm (at least for me) on the latest Ubuntu with the latest openrazor (3.4.0). I saw that 3.5 was just cut like 2 hours before this comment so I just tested that on mine. For reference:

```
wyatt@lazarus ~/Downloads $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

wyatt@lazarus ~/Downloads $ lsusb | grep 1532
Bus 002 Device 046: ID 1532:025a Razer USA, Ltd Razer BlackWidow V3 Pro
```

I think you can close this issue (though I'm not the originator of it) unless there's something specific about Ubuntu 21.10.

I also want to clarify the mechanical performance issues I experienced with both the volume wheel as well as the volume mute button were resolved with cleaning (which this issue was the only place I found a reference originally to this issue). For future defect hunters, I used `CRC QD Contact Cleaner, 11 Wt Oz, Industrial Strength, Quick Drying, No Residue, Plastic-Safe Electronics Cleaner, Safe For Sensitive Electronics, Aerosol Spray`;  however, this comment does not endorse any specific product. I'm sure any appropriate contact cleaner that is plastic safe will function equally as well.

**Comment by z3ntu** [comment]
Okay, let's close. If somebody sees this issue on other keyboards, please open a separate issue with the info which exact device you're using. And please try recent OpenRazer versions (v3.4.0 or v3.5.0)

**Comment by borgdylan** [comment]
This issue is still happening to me on the Blackwidow Elite.

```
dylan@ubuntu-server:~$ lsusb | grep 1532
Bus 001 Device 005: ID 1532:005c Razer USA, Ltd DeathAdder Elite
Bus 001 Device 003: ID 1532:0228 Razer USA, Ltd BlackWidow Elite
```

```
dylan@ubuntu-server:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Mantic Minotaur (development branch)
Release:	23.10
Codename:	mantic
```

```
dylan@ubuntu-server:~$ uname -a
Linux ubuntu-server 6.5.1 #1 SMP PREEMPT_DYNAMIC Wed Sep  6 19:24:17 CEST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Using openrazer 3.6.1

**Comment by z3ntu** [comment]
@borgdylan Weird, the device is in the list of devices where this should be fixed: https://github.com/openrazer/openrazer/blob/master/driver/razerkbd_driver.c#L3474

Anyways, as written in my last comment please open a new issue for this and don't necrobump issues.
