### ISSUE TITLE
Sensitivity buttons snaps DPI back to 2600.

### ISSUE THREAD

**Issue by music-cat-bread** [openrazer/razer-drivers#1882]
### Distribution

Manjaro Linux 21.3.6

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I have `Razer Basilisk` and I configured it's DPI levels as follows:
`800 1000 1200 1400 1600`
And it seems that it was applied, but after pressing the any of two sensitivity buttons located in the middle of the mouse snaps DPI back to it's default `2600` and won't change unless I manually do it from my computer.
Also I am using `Polychromatic` as a front-end.

Thanks in advice!

**Comment by lah7** [comment]
It's expected behaviour at the moment. OpenRazer doesn't currently intercept the DPI buttons in software, so these buttons are stuck with the hardware's factory presets. 

Only a handful of mice have the capability of saving a custom range of "DPI stages" to the firmware. It seems a few more mice might have support for this hardware feature (#1876)

**Comment by music-cat-bread** [comment]
Okay thanks for the info.
