### ISSUE TITLE
Support for Razor Kiyo Webcam

### ISSUE THREAD

**Issue by Smokemic** [openrazer/razer-drivers#1910]
if there is a way pls help

**Comment by lah7** [comment]
According to the discussion in [#1665](https://github.com/openrazer/openrazer/issues/1665#issuecomment-985784694), there wasn't any Razer-specific that OpenRazer could support for the Razor Kiyo Pro. Since it's just a USB webcam, it uses a different driver.

There is a project that offers controls for the Razer Kiyo Pro - it might work with the non-Pro model too:

https://github.com/soyersoyer/cameractrls
