### ISSUE TITLE
saving issue

### ISSUE THREAD

**Issue by AmirHossein143** [openrazer/razer-drivers#2076]
hi, I have been using Openrazer in Ubuntu 22.04 with Polychromatic about one week and every time i restart my computer the brightness and color and low power and such things reset and every time i have to define the settings again and again, i have razor viper ultimate.
although it does save the dpi configurations.

**Comment by stephanlachnit** [comment]
Same for me, Razer DeathAdder V3 Pro (Wireless).  Looking at `cat ~/.config/openrazer/persistence.conf`:

```
[PM2252H26600491]
dpi_x = 1600
dpi_y = 1600
poll_rate = 1000

[PM2013F34901480]
backlight_active = True
backlight_brightness = 100
backlight_effect = static
backlight_colors = 0 255 255 0 255 255 0 0 255
backlight_speed = 1
backlight_wave_dir = 1

[UNKWN000000003100]
dpi_x = 1800
dpi_y = 1800
poll_rate = 500

[UNKWN000000000450]
dpi_x = 1600
dpi_y = 1600
poll_rate = 1000

[UNKWN000000000172]
dpi_x = 1800
dpi_y = 1800
poll_rate = 500

[UNKWN000000000837]
dpi_x = 1800
dpi_y = 1800
poll_rate = 500

[UNKWN000000002944]
dpi_x = 1800
dpi_y = 1800
poll_rate = 500
```

It seems like it always adds a new device.

**Comment by lah7** [comment]
Unfortunately, these devices don't always respond when requested for something like the serial number, so the fallback is `UNKWN********`.

**Possible workarounds:**

* If the device is capable of remembering hardware settings between power cycles, turn off persistence in `~/.config/openrazer/razer.conf`. This would stop it from restoring to defaults (spectrum) every time the daemon starts when the serial is unknown.
  
  ```ini
  [Startup]
  restore_persistence = False
  ```

* If that does not work, since the OP is using Polychromatic, you could add a few `polychromatic-cli` to your Start-up Applications in Ubuntu and have the device set up that way. 
  * The alternate is to [use the OpenRazer Python library directly](https://github.com/openrazer/openrazer/tree/master/examples).

**Comment by Kyr4l** [comment]
that's a duplicaate of #2048

**Comment by z3ntu** [comment]
Closing as per previous comment.
