### ISSUE TITLE
Razer Nari corrupted firmware

### ISSUE THREAD

**Issue by Faustzen** [openrazer/razer-drivers#2133]
### Support

- [ ] Have you tried rebooting?
- [ ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hello am new in this proyect i got a nari headset for some time and one day it decided to stop working i tried the firmware updater but it wont recognize when conected on usb it display something like generic usb device i can use it with the 3.5 jack and it will turn on and everything but it wont pair with the dungle is there any way i could repair the firmware on linux?

**Comment by lah7** [comment]
Unfortunately, OpenRazer doesn't support firmware updates. You'll [need to use a Windows computer](https://mysupport.razer.com/app/answers/detail/a_id/1640/~/razer-nari-firmware-updater-%7C-rz04-02680) for this. It shouldn't be a virtual machine with USB passthrough since that's too risky and may end up bricking it.

If you are using Linux, open the Terminal and run:

    lsusb

There should be a device name & USB PID. This might identify if it's stuck in firmware (DFU) mode or definitely became a generic device (at that point, no software will see it as a Razer Nari so updater doesn't start). Not sure with headsets if there is a way to exit that mode.

Judging from [this thread](https://insider.razer.com/audio-10/razer-nari-ultimate-dongle-bricked-50056), you might not be alone with this issue.
