### ISSUE TITLE
Installing openrazr and polychrome, then uninstallin stops keyboard wake

### ISSUE THREAD

**Issue by VikOlliver** [openrazer/razer-drivers#2142]
### Distribution
Ubuntu 20.04 

### Support

- [x ] Have you tried rebooting?
- [x ] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hardware: OrnataV3, HP G4 laptop
Installing openrazr drivers and polychrome via Ubuntu ppa, then uninstalling them prevents the keyboard from waking the laptop from sleep.

All USB devices have wakeup enabled in /sys/bus/usb/devices/*/power, XHC is enabled in /proc/acpi/wakeup, screensaver is xscreensaver set to blank only. Wakeup with kbd and mouse worked before install,doesn't work after install/remove. Lifting lid will cause wakeup. If suspended with laptop open,  tapping laptop keyboard will now no longer cause a wakeup either.

As yet I have no fix.

**Comment by lah7** [comment]
Might be a coincidence for _OpenRazer_ to break wake from sleep functionality since the driver doesn't mess with that. Especially that other non Razer hardware (built in keyboard, trackpad and presumably USB mouse) were affected. I'd suspect the kennel was upgraded.

Have you checked the laptop's BIOS settings for power management related settings that control wake from sleep? (May be called "wake event"). There may be an option to set "who" is in charge (BIOS or OS) - if there's such option, try "BIOS" as I found my desktop PC wouldn't wake from USB when set to "OS".

Just to check, are you dual booting with Windows?
