### ISSUE TITLE
Razer Cynosa V2 Euro Truck Simulator 2 RGB functions passthrough.

### ISSUE THREAD

**Issue by JN19aban** [openrazer/razer-drivers#2224]
### O/S: Opensuse Leap 15.5

Hi,

I am testing the Euro Truck Simulator 2 on Opensuse and Ubuntu but it seems that not passthrough the RGB functions provided from Euro Truck. 

A small example is that on Windows is working fine. 

Maybe someone has make it work?

Best regards.

**Comment by lah7** [comment]
Hi. Sadly, OpenRazer doesn't support the [Razer Chroma SDK](https://developer.razer.com/works-with-chroma/download/) right now. It's also looking unlikely that games would work anyway since it appears Razer's Chroma SDK library is only included in the Windows builds of games.

See also:

* #1264

Will close this issue to avoid duplication. Follow #1264 for any updates 🔔
