### ISSUE TITLE
Support for razer ornata v3 028f (arch)

### ISSUE THREAD

**Issue by Tyrakis66** [openrazer/razer-drivers#2309]
### Affected Device / PID

Razer Ornata V3, 1532:028f

polychromatic doesn't see my keyboard at all, I tried to find any solution on github, none of them worked
![Screenshot_23-Sep_17-21-36_19138](https://github.com/user-attachments/assets/0883d425-ef75-4b74-8699-6cfa2ced244c)

Name: Razer Ornata v3
Product Number: RZ03-04460100-R3M1
Model Number: RZ03-0446

[OrnataV3_information_device.txt](https://github.com/user-attachments/files/17101275/OrnataV3_information_device.txt)

**Comment by lah7** [comment]
The `028F` variant isn't supported yet (even though there is another device sharing the same name). The good news is that there is a pull request implementing support and will appreciate the testing:

* https://github.com/openrazer/openrazer/pull/2233

Until it's added to a future release, you'll need to build a package using their branch (#2233). Since you're using Arch, take a look at [these instructions](https://github.com/openrazer/openrazer/wiki/Building-a-package#build-packages-from-a-different-github-repository). The source you'll want is:

    ssource=("git+https://github.com/tulser/openrazer#branch=ornata-v3-support")
